
services:
  db:
    image: mysql:8.0
    container_name: appsDB
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - ./storage/mysql-data:/var/lib/mysql

    environment:
      MYSQL_ROOT_PASSWORD: helloworld

  app:
    depends_on:
      - db
    image: phpmyadmin
    container_name: myadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db